### ISSUE TITLE
Doing it ourself

### ISSUE THREAD

**Issue by pktippa** [ajithvasudevan/WemosServoMotorControl#1]
Could you please elaborate more on Doing it ourself.
Explaining more about where do we get this motors, how connections are made, how to deploy the code and others.

**Comment by ajithvasudevan** [comment]
You can buy all parts for this project and other projects like these, online, e.g., amazon.in. Just search on Amazon for the name of the part.

Connections are made based on a schematic diagram, which you know based on experience, or you look it up on the internet. As for actually doing it, you need to get your hands dirty. There's no easy way to describe it  :)

You deploy code to the MCU (Micro Controller Unit), e.g., Wemos, using a USB-connected computer running a suitable IDE. In this case, the Arduino IDE. If the code compiles, it is a matter of clicking a button in the IDE while a USB cable connects the PC to the MCU board. 

That said, if you are a total beginner in this field, then I suggest you get some hands-on experience by being there with someone doing a project like this, watching them, and asking questions. Watching someone do it is a good way to learn the more practical aspects of DIY projects like these. Describing those basics on a quick and dirty Github project like this is probably "beyond the scope" and even if done, won't do much to get you the experience you need to get the confidence to do it on your own.

The next best thing you can do other than actually watching someone do projects like these, and which is way better than reading descriptions of how to do this, is to watch the hundreds of videos of tutorials and people doing similar projects on Youtube. Some examples here:

https://www.youtube.com/watch?v=nL34zDTPkcs   -- Introduction to Arduino for Beginners
https://www.youtube.com/watch?v=q2k3CzT5qE0  -- Introduction to Wemos D1 Mini
https://www.youtube.com/watch?v=kZ9b31gVemc  -- Controlling Servo motor with Arduino

Hope this helps!

**Comment by pktippa** [comment]
Well said Ajith. Thank you. 👍
